const ERROR_USERNAME_OR_PASSWORD_IS_NULL = "ERROR_USERNAME_OR_PASSWORD_IS_NULL";
const ERROR_USER_IS_EXSIT = "ERROR_USER_IS_EXSIT";

module.exports = {
  ERROR_USERNAME_OR_PASSWORD_IS_NULL,
  ERROR_USER_IS_EXSIT,
};
